apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmsak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 600m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfosmsak
        mountPath: /secrets/serviceuser
  env:
    - name: DOK_ARKIV_URL
      value: https://dokarkiv-q1.nais.preprod.local/rest/journalpostapi/v1/journalpost
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql